[pytest]
pythonpath = .
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated.*:DeprecationWarning
    ignore:.*anyio\.abc\.BlockingPortal alias is deprecated.*:DeprecationWarning
